### ISSUE TITLE
AzureStackStampDeploymentInfo.json is wrong name.

### ISSUE THREAD

**Issue by mattu0119** [MicrosoftDocs/azure-docs.ja-jp#1765]
[フィードバックをこちらに入力してください]
AzureStackStampDeploymentInfo.json is wrong file name.
AzureStackStampInformation.json is a correct name of the file.

Get-AzureStackStampInformation is correct cmdlet to obtain the information.
Get-AzureStackInfo is not correct.

https://docs.microsoft.com/en-us/azure/azure-stack/azure-stack-integrate-dns#get-dns-server-external-endpoint-information

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 4cf7c779-041d-a232-b441-b769be1aaa67
* Version Independent ID: 620aa3f3-4351-5ad3-996e-38140d50f108
* Content: [Azure Stack とデータセンターの統合 - DNS](https://docs.microsoft.com/ja-jp/azure/azure-stack/azure-stack-integrate-dns)
* Content Source: [articles/azure-stack/azure-stack-integrate-dns.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/azure-stack/azure-stack-integrate-dns.md)
* Service: **azure-stack**
* GitHub Login: @jeffgilb
* Microsoft Alias: **jeffgilb**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #23016](https://github.com/MicrosoftDocs/azure-docs/issues/23016) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @mattu0119 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/23016.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
