### ISSUE TITLE
Dead link to CONTRIBUTING.md in README.md

### ISSUE THREAD

**Issue by watahani** [MicrosoftDocs/azure-docs.ja-jp#1772]
https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/.github/CONTRIBUTING.md is dead link in README.md

**Comment by CeciAc** [comment]
Hello, @watahani 

Your contribution is much appreciated. Our team reviewed your feedback and it appears that this issue has been already logged.
Please review pr https://github.com/MicrosoftDocs/azure-docs.ja-jp/issues/1772  For this reason we are closing this issue since it is duplicated.

Kind regards,
Microsoft DOCS International Team
