### ISSUE TITLE
"Storage Account Contributor" can access to the storage account.

### ISSUE THREAD

**Issue by nakamacchi** [MicrosoftDocs/azure-docs.ja-jp#1845]
The description says that "Lets you manage storage accounts, but not access to them." But it is wrong.
The "Storage Account Contributor" built-in role can manage the storage accounts, and also can access to them. (Because this built-in role doesn't reject the data read/write actions.)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 99581afb-7950-6daa-7227-055d04446b7e
* Version Independent ID: f1a5bf89-9e54-aede-3a9a-70788a95927b
* Content: [Azure リソースの組み込みロール](https://docs.microsoft.com/ja-jp/azure/role-based-access-control/built-in-roles#storage-blob-data-owner-preview)
* Content Source: [articles/role-based-access-control/built-in-roles.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/role-based-access-control/built-in-roles.md)
* Service: **role-based-access-control**
* GitHub Login: @rolyon
* Microsoft Alias: **rolyon**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #23222](https://github.com/MicrosoftDocs/azure-docs/issues/23222) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @nakamacchi 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/23222

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
