### ISSUE TITLE
Please modify "AzureStackStampDeploymentInfo.JSON" and "Get-AzureStackInfo"

### ISSUE THREAD

**Issue by mattu0119** [MicrosoftDocs/azure-docs.ja-jp#2190]
I would like to suggest you to modify below.
1, AzureStackStampDeploymentInfo.JSON =&gt; AzureStackStampInformation.json
2, Get-AzureStackInfo =&gt; Get-AzureStackStampInformation

https://docs.microsoft.com/ja-jp/azure/azure-stack/azure-stack-integrate-identity#active-directory-federation-services-and-graph
 Azure Stack のメタデータ エンドポイントは AzureStackStampDeploymentInfo.JSON ファイルに、または特権エンドポイントを介してコマンド Get-AzureStackInfo を実行することで記載されます。

Thanks!

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: fac2cea8-637a-a642-7d7b-015c294976dd
* Version Independent ID: 37926dfc-778f-91ed-3f63-3782c3aa0a92
* Content: [Azure Stack とデータセンターの統合 - ID](https://docs.microsoft.com/ja-jp/azure/azure-stack/azure-stack-integrate-identity)
* Content Source: [articles/azure-stack/azure-stack-integrate-identity.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/azure-stack/azure-stack-integrate-identity.md)
* Service: **azure-stack**
* GitHub Login: @PatAltimore
* Microsoft Alias: **patricka**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #25688](https://github.com/MicrosoftDocs/azure-docs/issues/25688) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @mattu0119 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/25688

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
