### ISSUE TITLE
Change the width of table please

### ISSUE THREAD

**Issue by KeiroKamioka0000** [MicrosoftDocs/azure-docs.ja-jp#2206]
Hello, If possible, I would like to suggest to change the width of the table.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 7eaaf7c7-c1fe-1afc-e7f8-bc0e90044fb8
* Version Independent ID: 6461936a-3f5d-c2fe-cb37-e40fc9dc929e
* Content: [Azure Load Balancer の概要](https://docs.microsoft.com/ja-jp/azure/load-balancer/load-balancer-overview)
* Content Source: [articles/load-balancer/load-balancer-overview.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/load-balancer/load-balancer-overview.md)
* Service: **load-balancer**
* GitHub Login: @KumudD
* Microsoft Alias: **kumud**

**Comment by CeciAc** [comment]
Hello, @KeiroKamioka0000 

Your contribution is much appreciated. Our team reviewed your feedback and it appears that this issue has been already logged.
Please review issue https://github.com/mspnp/architecture-center.ja-jp/issues/32 
For this reason, we are closing this issue since it is duplicated.

Kind regards,
Microsoft DOCS International Team
