### ISSUE TITLE
missing codes

### ISSUE THREAD

**Issue by linyixian** [MicrosoftDocs/azure-docs.ja-jp#2229]
CustomVison Tutorial: Run TensorFlow model in Python Japanese
Missing part of the code in the document.

Step: Load your model and tags
----------------------------------------------------------------------------------------

graph_def = tf.GraphDef()
labels = []

#### These are set to the default names from exported models, update as needed.
filename = "model.pb" <---------- missing
labels_filename = "labels.txt" <---------- missing

---
Please correct

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 754dd7d5-dd8b-4a75-5d79-0ba621a847cd
* Version Independent ID: 3cca3535-1c16-2da1-46c6-421cbf808bc3
* Content: [チュートリアル:Python での TensorFlow モデルの実行 - Custom Vision Service](https://docs.microsoft.com/ja-jp/azure/cognitive-services/custom-vision-service/export-model-python)
* Content Source: [articles/cognitive-services/Custom-Vision-Service/export-model-python.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/cognitive-services/Custom-Vision-Service/export-model-python.md)
* Service: **cognitive-services**
* GitHub Login: @areddish
* Microsoft Alias: **areddish**

**Comment by CeciAc** [comment]
Hello, @linyixian 

Your contribution is much appreciated. Our team reviewed your feedback and it appears that this issue has been already logged.
Please review issue https://github.com/MicrosoftDocs/azure-docs/issues/27433 
For this reason we are closing this issue since it is duplicated.

Kind regards,
Microsoft DOCS International Team
