### ISSUE TITLE
Part of getting azure subscription id(sample script) contains mistake

### ISSUE THREAD

**Issue by geforce-hisa0904** [MicrosoftDocs/azure-docs.ja-jp#2250]
Regarding "create-vms-with-docker-machine" section, I guess that part of getting azure subscription id(sample script) contains mistake.
This script can not execute.
Could you confirm it?

Current:
``sub=$(az account show --query "id" -o tsv)``
suggestion:
``$sub=$(az account show --query "id" -o tsv)``

[フィードバックをこちらに入力してください]

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 4b439325-8922-359a-9f55-e4a5bdf06339
* Version Independent ID: bb0f278c-8ea5-7656-be77-ed93ac9884d7
* Content: [Docker マシンを使用して Azure で Linux ホストを作成する](https://docs.microsoft.com/ja-jp/azure/virtual-machines/linux/docker-machine#create-vms-with-docker-machine)
* Content Source: [articles/virtual-machines/linux/docker-machine.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/virtual-machines/linux/docker-machine.md)
* Service: **virtual-machines-linux**
* GitHub Login: @cynthn
* Microsoft Alias: **cynthn**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #28259](https://github.com/MicrosoftDocs/azure-docs/issues/28259) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @geforce-hisa0904 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/28259

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
