### ISSUE TITLE
Language support

### ISSUE THREAD

**Issue by koichi-nakajima** [MicrosoftDocs/azure-docs.ja-jp#2318]
Do you have any plan to support other language pairs in Custom Translator which do not include English, such as between German and French?

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 3452c464-0135-aaab-5e96-a88f3144e378
* Version Independent ID: 3816f475-bf5f-b5b4-9458-5cc70e93d55e
* Content: [言語サポート - Translator Text API - Azure Cognitive Services](https://docs.microsoft.com/ja-jp/azure/cognitive-services/translator/language-support#feedback)
* Content Source: [articles/cognitive-services/Translator/language-support.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/cognitive-services/Translator/language-support.md)
* Service: **cognitive-services**
* Sub-service: **translator-text**
* GitHub Login: @Jann-Skotdal
* Microsoft Alias: **v-jansko**

**Comment by CeciAc** [comment]
Hello, @koichi-nakajima 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team

**Comment by Jann-Skotdal** [comment]
@koichi-nakajima: You can create 2 models and then automatically pivot between languages.  For example, between French and German:

Prerequisites
•	Select the workspace you wish to use. Both models need to be in the same workspace
•	Select the project label you wish to use. Both models must have the same project label, or both models must not have a project label.  
•	Select the category you wish to use. Both models must have the same category

Essentially, the two models must have the same complete Category ID.  The only difference is the language pair.

Train and deploy both the French->English and English->German system.

Calls through the API where from=FR, to=DE and CategoryID=<selected category id> will pivot through the two models in order to deliver the German output.

We are working on adding this information to the documentation.
