### ISSUE TITLE
This page includes environment specific explanations

### ISSUE THREAD

**Issue by rioriost** [MicrosoftDocs/azure-docs.ja-jp#2469]
"C:" is a drive letter for Windows. And it's described in 'bash' quotation. It means the description works on Windows only. Could you add the descriptions for other platforms such as macOS / Linux?

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 995ff127-8028-8118-701e-53f07f3a7fc5
* Version Independent ID: dff7d0b8-f677-99a9-64b3-89d9bb4fde0d
* Content: [Azure Cosmos DB は:Python と SQL API によるアプリの構築](https://docs.microsoft.com/ja-jp/azure/cosmos-db/create-sql-api-python#feedback)
* Content Source: [articles/cosmos-db/create-sql-api-python.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/cosmos-db/create-sql-api-python.md)
* Service: **cosmos-db**
* Sub-service: **cosmosdb-sql**
* GitHub Login: @SnehaGunda
* Microsoft Alias: **sngun**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #29424](https://github.com/MicrosoftDocs/azure-docs/issues/29424) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @rioriost 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/29424

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
