### ISSUE TITLE
Export button location change.

### ISSUE THREAD

**Issue by v-maroge** [MicrosoftDocs/azure-docs.ja-jp#2492]
The Export button to acquire the SAS URL is currently under "Settings" of the operating system disk. We wish this part is updated. Thanks.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 218c3a24-424f-e928-d0c0-89c8b8349bc8
* Version Independent ID: 0ba31a4b-94cf-2b4f-1fbc-29a92fe7d97a
* Content: [Azure から Windows VHD をダウンロードする](https://docs.microsoft.com/ja-jp/azure/virtual-machines/windows/download-vhd#generate-sas-url)
* Content Source: [articles/virtual-machines/windows/download-vhd.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/virtual-machines/windows/download-vhd.md)
* Service: **virtual-machines-windows**
* GitHub Login: @cynthn
* Microsoft Alias: **cynthn**

**Comment by CeciAc** [comment]
Hello, @v-maroge

Your contribution is much appreciated. Our team reviewed your feedback and it appears that this issue has been already logged.
Please review issue https://github.com/MicrosoftDocs/azure-docs/issues/29784 . For this reason we are closing this issue since it is duplicated.

Kind regards,
Microsoft DOCS International Team

**Comment by Daya-Patil** [comment]
pls Refer https://github.com/MicrosoftDocs/azure-docs/pull/29997
