### ISSUE TITLE
Kubernetes クラスターを定義する

### ISSUE THREAD

**Issue by misterturtleneck** [MicrosoftDocs/azure-docs.ja-jp#2588]
プログラムのミス。
    tags {
        Environment = "Development"
    }

ではなく、
    tags = {
        Environment = "Development"
    }

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: c22b6ec6-7a27-4029-ff8f-674a40c0e552
* Version Independent ID: bd2884f3-831a-3761-0502-5eb1594872bd
* Content: [Azure Kubernetes Service (AKS) および Terraform を使用して Kubernetes クラスターを作成する](https://docs.microsoft.com/ja-jp/azure/terraform/terraform-create-k8s-cluster-with-tf-and-aks#define-a-kubernetes-cluster)
* Content Source: [articles/terraform/terraform-create-k8s-cluster-with-tf-and-aks.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/terraform/terraform-create-k8s-cluster-with-tf-and-aks.md)
* Service: **azure**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by CeciAc** [comment]
Hello, @misterturtleneck 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/33032

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
