### ISSUE TITLE
License Requirements need clarification

### ISSUE THREAD

**Issue by UKayo** [MicrosoftDocs/azure-docs.ja-jp#2605]
Per below, any target user to be licensed with this feature needs to be licensed with AAD Basic and over or O365 E3 or over. Please update so that this is clear on this page as well. (The current statement is unclear if we can just 1 license to cover the usage)
https://techcommunity.microsoft.com/t5/Azure-Active-Directory-Identity/Announcing-the-public-preview-of-Azure-AD-group-based-license/ba-p/245210

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: d215ddd2-d71f-8b91-c5f7-314c6287cafc
* Version Independent ID: ef317dea-e56a-e6db-3344-67aa028a0ca7
* Content: [グループベースのライセンスとは - Azure Active Directory](https://docs.microsoft.com/ja-jp/azure/active-directory/fundamentals/active-directory-licensing-whatis-azure-portal#feedback)
* Content Source: [articles/active-directory/fundamentals/active-directory-licensing-whatis-azure-portal.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/active-directory/fundamentals/active-directory-licensing-whatis-azure-portal.md)
* Service: **active-directory**
* Sub-service: **fundamentals**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by CeciAc** [comment]
Hello, @UKayo 

Your contribution is much appreciated. Our team reviewed your feedback and it appears that this issue has been already logged.
Please review issue https://github.com/MicrosoftDocs/azure-docs/issues/27331 
For this reason we are closing this issue since it is duplicated.

Kind regards,
Microsoft DOCS International Team
