### ISSUE TITLE
Invalid XML format

### ISSUE THREAD

**Issue by t104** [MicrosoftDocs/azure-docs.ja-jp#2606]
This XML format is invalid.
# Configuring fixed-rate sampling in JAVA
    &lt;TelemetryProcessors&gt;
        &lt;BuiltInProcessors&gt;
            &lt;Processor type = "FixedRateSamplingTelemetryProcessor"&gt;
                &lt;!-- Set a percentage close to 100/N where N is an integer. --&gt;
                &lt;!-- E.g. 50 (=100/2), 33.33 (=100/3), 25 (=100/4), 20, 1 (=100/100), 0.1 (=100/1000) --&gt;
                &lt;Add name = "SamplingPercentage" value = "50" /&gt;
            &lt;/Processor&gt;
        &lt;/BuiltInProcessors&gt;
    &lt;TelemetryProcessors/&gt;

The last line should be
&lt;/TelemetryProcessors&gt;

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 2f4c906d-7abe-eab7-331a-120230344583
* Version Independent ID: ab24ade5-5e4c-b430-c3f8-2a00073e9e81
* Content: [Azure Application Insights におけるテレメトリ サンプリング](https://docs.microsoft.com/ja-jp/azure/azure-monitor/app/sampling#types-of-sampling)
* Content Source: [articles/azure-monitor/app/sampling.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/azure-monitor/app/sampling.md)
* Service: **application-insights**
* GitHub Login: @cijothomas
* Microsoft Alias: **cithomas**

**Comment by CeciAc** [comment]
Hello, @t104 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/33514

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
