### ISSUE TITLE
PowerShellコマンドの最新化

### ISSUE THREAD

**Issue by terasawa-ippei** [MicrosoftDocs/azure-docs.ja-jp#2607]
Disable-AzureRmContextAutosave、Connect-AzureRmAccount など本ドキュメント内で利用されているコマンドは
現在の環境で実行するとCommandNotFoundException が返り、実行できないため確認と訂正をお願いします。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 038d927f-2bcc-c62d-b3c3-f194513bced6
* Version Independent ID: 41adf2c5-3ab7-7387-e541-89e34aa6a6b1
* Content: [Azure Automation での初めての PowerShell Runbook](https://docs.microsoft.com/ja-jp/azure/automation/automation-first-runbook-textual-powershell#feedback)
* Content Source: [articles/automation/automation-first-runbook-textual-powershell.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/automation/automation-first-runbook-textual-powershell.md)
* Service: **automation**
* Sub-service: **process-automation**
* GitHub Login: @georgewallace
* Microsoft Alias: **gwallace**

**Comment by georgewallace** [comment]
@terasawa-ippei Make sure you have the latest modules in your account.

**Comment by terasawa-ippei** [comment]
@georgewallace 
Thanks for the hint. It seems that the version of Automation's standard module is old. If possible, can you consider appending that the module needs updating?

**Comment by CeciAc** [comment]
Hello, @terasawa-ippei

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/33600

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
