### ISSUE TITLE
miss schedule cron setting

### ISSUE THREAD

**Issue by tsaeki** [MicrosoftDocs/azure-docs.ja-jp#2715]
https://docs.microsoft.com/ja-jp/azure/azure-functions/functions-bindings-timer#java-example

Good
schedule = "0 */5 * * * *

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: b5527c3b-a5da-c73d-66c2-20d96003ff7c
* Version Independent ID: 42154c7b-b0e0-26db-79bc-3f1673c48e40
* Content: [Azure Functions のタイマー トリガー](https://docs.microsoft.com/ja-jp/azure/azure-functions/functions-bindings-timer#java-example)
* Content Source: [articles/azure-functions/functions-bindings-timer.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/azure-functions/functions-bindings-timer.md)
* Service: **azure-functions**
* GitHub Login: @craigshoemaker
* Microsoft Alias: **cshoe**

**Comment by srvbpigh** [comment]
Hello, @tsaeki
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #36508](https://github.com/MicrosoftDocs/azure-docs/issues/36508) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @tsaeki

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/36508

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
