### ISSUE TITLE
"azure-iot-sdk-c" install opration has been changed.

### ISSUE THREAD

**Issue by ahidaka** [MicrosoftDocs/azure-docs.ja-jp#2839]
See the details as https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/devbox_setup.md#windows
"git clone https://github.com/Azure/azure-iot-sdk-c.git --recursive" doesn't work properly.
Need "git submodule update --init" before "mkdir cmake"

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 4b925506-63fb-b986-468a-465f8274f5b1
* Version Independent ID: 2687c603-a1ec-8ec7-f37e-fa62de94251b
* Content: [シミュレートされた TPM デバイスを C を使用して Azure IoT Hub にプロビジョニングする](https://docs.microsoft.com/ja-jp/azure/iot-dps/quick-create-simulated-device)
* Content Source: [articles/iot-dps/quick-create-simulated-device.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/iot-dps/quick-create-simulated-device.md)
* Service: **iot-dps**
* GitHub Login: @wesmc7777
* Microsoft Alias: **wesmc**

**Comment by lichasu** [comment]
Issue moved to [MicrosoftDocs/azure-docs #39810](https://github.com/MicrosoftDocs/azure-docs/issues/39810) via [**ZenHub**](https://www.zenhub.com/)

**Comment by lichasu** [comment]
Hello, @ahidaka 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/39810.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
