### ISSUE TITLE
vnetPE

### ISSUE THREAD

**Issue by meatloaf111** [MicrosoftDocs/azure-docs.ja-jp#2887]
Following command should use $rgName instead of the value of the resource groupname it self.

$vnetPE = New-AzVirtualNetwork `
-Name $virtualNetworkNamePE `
-ResourceGroupName myResourceGroup `

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 25c87883-1e32-6383-9d21-306f91406ba6
* Version Independent ID: ba6f8deb-cbfc-bf07-2bc8-26f5e6145859
* Content: [Azure PowerShell を使用して Azure プライベート リンク サービスを作成する](https://docs.microsoft.com/ja-jp/azure/private-link/create-private-link-service-powershell#feedback)
* Content Source: [articles/private-link/create-private-link-service-powershell.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/private-link/create-private-link-service-powershell.md)
* Service: **private-link**
* GitHub Login: @KumudD
* Microsoft Alias: **kumud**

**Comment by srvbpigh** [comment]
Hello, @meatloaf111
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @meatloaf111 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/41707

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
