### ISSUE TITLE
The Ja-JP page has an incorrect translation ("非推奨")

### ISSUE THREAD

**Issue by ms-stakaha** [MicrosoftDocs/azure-docs.ja-jp#4276]
In Top important information, it writes regarding Deprecation Process of old Azure AD Connect. This information has translated "Deprecation" as "非推奨". In this case, "Deprecation" should be translated as "廃止"
The following docs has translated "Deprecations" as "廃止". It is correct translation. This page should also be change from "非推奨" to "廃止".

  Ja-JP page : "廃止"
  https://docs.microsoft.com/ja-jp/azure/active-directory/fundamentals/whats-new#october-2019
  
  en-us page : "detections"
  https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/whats-new#october-2019

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 57f5478b-3132-21d0-a420-a1140db235de
* Version Independent ID: 266bbd16-2117-f680-6493-e183eb09fdbc
* Content: [Azure AD Connect:バージョンのリリース履歴](https://docs.microsoft.com/ja-jp/azure/active-directory/hybrid/reference-connect-version-history#feedback)
* Content Source: [articles/active-directory/hybrid/reference-connect-version-history.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/active-directory/hybrid/reference-connect-version-history.md)
* Service: **active-directory**
* Sub-service: **hybrid**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by srvbpigh** [comment]
Hello, @ms-stakaha
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @ms-stakaha 

Thank you for your linguistic feedback. 
 
Unfortunately, after reviewing your feedback our linguistic team considered it to be not fully aligned with our criteria for acceptance because: **The suggested term 廃止する means to discontinue while we use the term "deprecation" to indicate a software feature or programming object that is outdated and should not be used. We believe that 非推奨 should better represents the state.**
We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback. 

Kind regards,
Microsoft DOCS International Team

**Comment by murasamelabo** [comment]
Hi CeciAc,

I would like to confirm "deprecation/非推奨" mean.
Will Old Version AADC User be still provided support after 2020/11 from Microsoft Product team officially?

As far as I understand "非推奨" mean is "not recommended"  in japan.
When we create support ticket after 2020/11 for older version,  If we awill be suggested to update newer before providing  any support, it is not "非推奨". it is "not supported".
