### ISSUE TITLE
better to add notice: store db connection string to environment variable again 

### ISSUE THREAD

**Issue by hnakayam** [MicrosoftDocs/azure-docs.ja-jp#4551]
When update and test the ASP.NET core code in the later time, the developer must set DB connection string to Environment Variable again in the newly opened development shell (cmd, bash or powershell).

https://docs.microsoft.com/ja-jp/azure/app-service/containers/tutorial-dotnetcore-sqldb-app#test-your-changes-locally

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 48a90540-55d7-99ae-7a47-6cf8e526d631
* Version Independent ID: 190e73c1-7711-05d2-afeb-5565d7a3dd37
* Content: [チュートリアル:SQL DB を使用する Linux ASP.NET Core](https://docs.microsoft.com/ja-jp/azure/app-service/containers/tutorial-dotnetcore-sqldb-app#feedback)
* Content Source: [articles/app-service/containers/tutorial-dotnetcore-sqldb-app.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/app-service/containers/tutorial-dotnetcore-sqldb-app.md)
* GitHub Login: @OpenLocalizationService

**Comment by srvbpigh** [comment]
Hello, @hnakayam
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #54865](https://github.com/MicrosoftDocs/azure-docs/issues/54865) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @hnakayam, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/54865. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
