### ISSUE TITLE
`cephalin-core` is wrong.  `<server-name>` is right.

### ISSUE THREAD

**Issue by Soichi-Fukasawa** [MicrosoftDocs/azure-docs.ja-jp#4627]
At "Create connection string"

```
az sql db show-connection-string --client ado.net --server cephalin-core --name coreDB
```

Probably, `cephalin-core` is come from @cephalin .
Please change `cephalin-core` to `<server-name>`.

This problem is same in English version.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 00961883-36eb-f736-b906-73d4c35e69b0
* Version Independent ID: 3a2fd493-9682-eedf-fad1-571b9391cd46
* Content: [チュートリアル:ASP.NET Core と SQL Database](https://docs.microsoft.com/ja-jp/azure/app-service/app-service-web-tutorial-dotnetcore-sqldb#feedback)
* Content Source: [articles/app-service/app-service-web-tutorial-dotnetcore-sqldb.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/app-service/app-service-web-tutorial-dotnetcore-sqldb.md)
* GitHub Login: @olprod

**Comment by srvbpigh** [comment]
Hello, @Soichi-Fukasawa
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @Soichi-Fukasawa, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/55930. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
