### ISSUE TITLE
Request for error correction - Description of "FORCE LAST GOOD PLAN"

### ISSUE THREAD

**Issue by axis5150** [MicrosoftDocs/azure-docs.ja-jp#551]
The following statement is in section "Automatic tuning options" 
------
FORCE LAST GOOD PLAN - identifies SQL queries using execution plan that is slower than the previous good plan, and queries using the last known good plan instead of the regressed plan. Default Azure setting for this option is enabled.
------
Describe "Default Azure setting for this option is enabled." is mistake, "Default Azure setting for this option is disabled." is correct for now.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: ea14cd16-0e66-d9ea-6ad3-3246cb380e87
* Version Independent ID: 0767f70f-62f7-c74c-3af2-7bba6dc651d4
* Content: [Azure SQL Database - 自動チューニング](https://docs.microsoft.com/ja-jp/azure/sql-database/sql-database-automatic-tuning#feedback)
* Content Source: [articles/sql-database/sql-database-automatic-tuning.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/sql-database/sql-database-automatic-tuning.md)
* Service: **sql-database**
* GitHub Login: @jovanpop-msft
* Microsoft Alias: **jovanpop**

**Comment by gosali** [comment]
Issue moved to [MicrosoftDocs/azure-docs #10572](https://github.com/MicrosoftDocs/azure-docs/issues/10572) via [**ZenHub**](https://www.zenhub.com/)

**Comment by gosali** [comment]
Hello, @axis5150 , 

 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/10572. 

 
We truly appreciate your contribution to our articles.  

 
Kind regards, 

Microsoft DOCS International Team

**Comment by axis5150** [comment]
@gosali  Thanks a lot!!
