### ISSUE TITLE
Add note about filesystem

### ISSUE THREAD

**Issue by sengokyu** [MicrosoftDocs/azure-docs.ja-jp#623]
I need a note about the filesystem. 
Azure file share mounted via SMB(CIFS), and lack of Linux capabilities which need by some applications (like latest MySQL/MariaDB).
Cannot persist that applications.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: b730fc95-951e-1acd-770d-88b3e6f2f6ef
* Version Independent ID: b6445fd2-46ea-aedd-2f2c-294faa660660
* Content: [Azure Container Instances での Azure Files ボリュームのマウント](https://docs.microsoft.com/ja-jp/azure/container-instances/container-instances-volume-azure-files)
* Content Source: [articles/container-instances/container-instances-volume-azure-files.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/container-instances/container-instances-volume-azure-files.md)
* Service: **container-instances**
* GitHub Login: @seanmck
* Microsoft Alias: **seanmck**

**Comment by LisandroSu** [comment]
Issue moved to [MicrosoftDocs/azure-docs #13023](https://github.com/MicrosoftDocs/azure-docs/issues/13023) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
Hello, @sengokyu , 
 
Your contribution is much appreciated. Your feedback is related to the original documentation. 
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/13023. 
 
We truly appreciate your contribution to our articles.  
 
Kind regards, 
Microsoft DOCS International Team
