### ISSUE TITLE
It does not mention Web Apps on Linux in document of "Enable logs", Although the "App Service on Linux Documentation" tree of link display the link of "Enable logs".

### ISSUE THREAD

**Issue by mekamata** [MicrosoftDocs/azure-docs.ja-jp#700]
It does not mention about Web Apps on Linux in document of "[Enable logs](https://docs.microsoft.com/en-us/azure/app-service/web-sites-enable-diagnostic-log?toc=%2fazure%2fapp-service%2fcontainers%2ftoc.json)", Although the "[App Service on Linux Documentation](https://docs.microsoft.com/en-us/azure/app-service/containers/)" tree of link display the link of "Enable logs".

It should be mention the specification of  Web Apps on Linux in the document of "Enable logs".
I think it can only use Docker Container Log in Web Apps on Linux.

 Thanks

**Comment by LisandroSu** [comment]
Issue moved to [MicrosoftDocs/azure-docs #14748](https://github.com/MicrosoftDocs/azure-docs/issues/14748) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
Hello, @mekamata ,

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/14748.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
