### ISSUE TITLE
out of sync wih the original content

### ISSUE THREAD

**Issue by kazshi** [MicrosoftDocs/azure-docs.ja-jp#733]
the following content is out of sync with its source connet - please check and fix appropriately.
https://docs.microsoft.com/ja-jp/azure/app-service/app-service-web-get-started-dotnet#update-the-app-and-redeploy
「上部の &lt;div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000"&gt; HTML タグを検索し、要素全体を次のコードに置き換えます。」
source:
"Replace the two &lt;div&gt; tags with the following code:"

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 3d445808-e61d-ccc2-3696-ef3ea109a662
* Version Independent ID: 8a9e706a-c350-1271-dcb8-883e166423b4
* Content: [Azure に C# ASP.NET Core Web アプリを作成する](https://docs.microsoft.com/ja-jp/azure/app-service/app-service-web-get-started-dotnet#update-the-app-and-redeploy)
* Content Source: [articles/app-service/app-service-web-get-started-dotnet.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/app-service/app-service-web-get-started-dotnet.md)
* Service: **app-service-web**
* GitHub Login: @cephalin
* Microsoft Alias: **cephalin**

**Comment by LisandroSu** [comment]
Hello, @<contributor's GITHUB name>,
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
Hello, @kazshi 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
Hello, @kazshi 

This file is being localized now and that's why it has differences with the source/English version. This process doesn't take very long, but because of the Triple Crown and Ignite events it may take a bit longer than usual for the new versions to be live. 

The new updated version should be available by October 14th.

Thanks again for your feedback.

Kind regards,
Microsoft DOCS International Team
