### ISSUE TITLE
incorrect locale

### ISSUE THREAD

**Issue by taoyama** [MicrosoftDocs/azure-docs.ja-jp#762]
In https://docs.microsoft.com/ja-jp/azure/dns/, some URL are linked to "it-it" locale.
They should be "ja-jp".

**Comment by LisandroSu** [comment]
Hello, @<contributor's GITHUB name>,

Your contribution is much appreciated. Our team reviewed your feedback and it appears that this issue has been already logged.
Please review issue #760 . For this reason we are closing this issue since it is duplicated.

This issue has already been fixed. You may be loading a cached version of the site.

Kind regards,
Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
Hello, @taoyama ,

Your contribution is much appreciated. Our team reviewed your feedback and it appears that this issue has been already logged.
Please review issue #760 . For this reason we are closing this issue since it is duplicated.

This issue has already been fixed. You may be loading a cached version of the site.

Kind regards,
Microsoft DOCS International Team
