### ISSUE TITLE
sending Notification to supecific Xamarin.Android Apps

### ISSUE THREAD

**Issue by JosephBrainstein** [MicrosoftDocs/azure-docs.ja-jp#924]
Hello, I wanna make this program using C#(xamarin.android), not java.
Is the tutorial not here?

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 7e71a428-6213-e0e1-cfba-76964353e0a2
* Version Independent ID: ef27b609-4c88-3a11-35ad-709df9c51861
* Content: [Azure Notification Hubs と Google Cloud Messaging を使用して特定の Android デバイスにプッシュ通知を送信する](https://docs.microsoft.com/ja-jp/azure/notification-hubs/notification-hubs-aspnet-backend-android-xplat-segmented-gcm-push-notification)
* Content Source: [articles/notification-hubs/notification-hubs-aspnet-backend-android-xplat-segmented-gcm-push-notification.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/notification-hubs/notification-hubs-aspnet-backend-android-xplat-segmented-gcm-push-notification.md)
* Service: **notification-hubs**
* GitHub Login: @dimazaid
* Microsoft Alias: **dimazaid**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #19669](https://github.com/MicrosoftDocs/azure-docs/issues/19669) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @JosephBrainstein 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/19669.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
